### ISSUE TITLE
Failed to scan android app code with the error "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by Securee** [MobSF/mobsfscan#22]
In a  Windows 10 x64, I install the mobsfscan by: pip3 install mobsfscan
and then try to scan an android app source code, but failed according to the error:
Traceback (most recent call last):
  File "d:\python380\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python380\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python380\Scripts\mobsfscan.exe\__main__.py", line 7, in <module>
  File "d:\python380\lib\site-packages\mobsfscan\__main__.py", line 65, in main
    scan_results = MobSFScan(
  File "d:\python380\lib\site-packages\mobsfscan\mobsfscan.py", line 79, in scan
    result = scanner.scan()
  File "d:\python380\lib\site-packages\libsast\scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "d:\python380\lib\site-packages\libsast\core_sgrep\semantic_sgrep.py", line 37, in scan
    self.format_output(sgrep_out)
  File "d:\python380\lib\site-packages\libsast\core_sgrep\semantic_sgrep.py", line 42, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable

The semgrep has upgraded to 0.69.1. I'm not sure this issue related to the semgrep not surpport x64 or not.

**Comment by lokkeshjaya** [comment]
I guess mobsfscan work with only **semgrep** version == **0.50.1**

I had a similar issue in my pipeline and finally resolved it by downgrading the **semgrep** to **0.50.1**

`python3 -m pip install semgrep==0.50.1`

**Comment by ajinabraham** [comment]
mobsfscan requires the exact pinned version of semgrep. New versions of semgrep might have APIs changed and that will break the integration.
