### ISSUE TITLE
Error !!! TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by effortlessdevsec** [MobSF/mobsfscan#39]
- Pattern Match ████████████████████████████████████████████████████████████ 8
- Semantic Grep  1
Traceback (most recent call last):
  File "c:\users\amitp\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\amitp\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\amitp\AppData\Local\Programs\Python\Python39\Scripts\mobsfscan.exe\__main__.py", line 7, in <module>
  File "c:\users\amitp\appdata\local\programs\python\python39\lib\site-packages\mobsfscan\__main__.py", line 65, in main
    scan_results = MobSFScan(
  File "c:\users\amitp\appdata\local\programs\python\python39\lib\site-packages\mobsfscan\mobsfscan.py", line 79, in scan
    result = scanner.scan()
  File "c:\users\amitp\appdata\local\programs\python\python39\lib\site-packages\libsast\scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "c:\users\amitp\appdata\local\programs\python\python39\lib\site-packages\libsast\core_sgrep\semantic_sgrep.py", line 41, in scan
    self.format_output(sgrep_out)
  File "c:\users\amitp\appdata\local\programs\python\python39\lib\site-packages\libsast\core_sgrep\semantic_sgrep.py", line 46, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable

**Comment by ajinabraham** [comment]
Windows is not supported

**Comment by SubGlitch1** [comment]
what about macOS
