### ISSUE TITLE
Error while running on an Android project

### ISSUE THREAD

**Issue by twittemb** [MobSF/mobsfscan#42]
Hi there,

First of all, thanks for this tool.

I have an issue while running it on an Android/Kotlin project with the following error.

Environment:
- macOS Monterey
- proc M1 Ultra
- Python 3.8.9 (default, May 17 2022, 12:55:41) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
- mobsfscan: v0.1.1

Does this ring a bell to you ?

Thanks a lot.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/common.py", line 45, in myrunner
    ret[0] = function(*args, **kwargs)
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/core_sgrep/helpers.py", line 50, in invoke_semgrep
    ) = semgrep_main.main(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/semgrep_main.py", line 363, in main
    rule_matches_by_rule, semgrep_errors, all_targets, profiling_data = run_rules(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/semgrep_main.py", line 154, in run_rules
    ) = core_runner.invoke_semgrep(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 758, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
    returncode = runner.execute()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 283, in execute
    rc = asyncio.run(self._stream_subprocess())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 257, in _stream_subprocess
    raise SemgrepError(f"Error while running rules: {r}")
semgrep.error.SemgrepError: Error while running rules: 0 bytes read on a total of 2 expected bytes
- Semantic Grep  5
Traceback (most recent call last):
  File "/Users/xxx/Library/Python/3.8/bin/mobsfscan", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/mobsfscan/__main__.py", line 65, in main
    scan_results = MobSFScan(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/mobsfscan/mobsfscan.py", line 79, in scan
    result = scanner.scan()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 41, in scan
    self.format_output(sgrep_out)
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 46, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ajinabraham** [comment]
Seems like a semgrep error.

```semgrep.error.SemgrepError: Error while running rules: 0 bytes read on a total of 2 expected bytes```
Please report it upstream
