### ISSUE TITLE
mobsfscan doesn't work on Windows

### ISSUE THREAD

**Issue by nibarius** [MobSF/mobsfscan#8]
Whenever trying to run mobsfscan on Windows (10) the Semantic Grep step fails with a traceback:

```
C:\src\audience-network\samples\android\AdUnitsSample\src\main\java\com\facebook\samples\AdUnitsSample>mobsfscan SampleListActivity.java
- Pattern Match ████████████████████████████████████████████████████████████ 1
- Semantic Grep  0
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Roaming\Python\Python38\Scripts\mobsfscan.exe\__main__.py", line 7, in <module>
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\mobsfscan\__main__.py", line 65, in main
    scan_results = MobSFScan(
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\mobsfscan\mobsfscan.py", line 78, in scan
    result = scanner.scan()
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\libsast\scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\libsast\core_sgrep\semantic_sgrep.py", line 37, in scan
    self.format_output(sgrep_out)
  File "C:\Users\me\AppData\Roaming\Python\Python38\site-packages\libsast\core_sgrep\semantic_sgrep.py", line 42, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ajinabraham** [comment]
mobsfscan is not supported in Windows as underlying semgrep doesn't support Windows yet.

**Comment by nibarius** [comment]
Maybe it's worth mentioning that Windows is not supported in the readme file?

**Comment by ajinabraham** [comment]
Sure, added a platform badge.
